apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
#parameters:
#  datastore: VSANDatastore
#  diskformat: thin
#  fstype: ext3
