pivotal:
  quotesService:
    name: quotes-service:8080
  accountsService:
    name: accounts-service:8080
eureka:
  client:
    enabled: false

dekorate:
  kubernetes:
    service-account: "config-reader"
    readiness-probe:
      initial-delay-seconds: 20
      http-action-path: "/actuator/health/readiness"
    liveness-probe:
      initial-delay-seconds: 10
      http-action-path: "/actuator/health/liveness"
    image-pull-policy: "IfNotPresent"
    service-type: "ClusterIP"
    version: "latest"

    env-vars:
      - name: "SPRING_PROFILES_ACTIVE"
        value: "kubernetes"
      - name: "SPRING_DATASOURCE_USERNAME"
        value: "root"
      - name: "SPRING_DATASOURCE_PASSWORD"
        value: "mysql-root-password"
        secret: "acme-mysql"


spring:
  datasource:
      url: jdbc:mysql://acme-mysql:3306/my_database
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
